### ISSUE TITLE
Missing usage instructions

### ISSUE THREAD

**Issue by DevanWolf** [Crawlerop/paftools#1]
People have trouble using this without a readme file. As a result, I get errors like mine:
```
Traceback (most recent call last):
  File "paf_decoder.py", line 90, in <module>
    file_buf = open(sys.argv[1], "rb")
  File "paf_decoder.py", line 151, in <module>
    output_file(canvas, f"{os.path.splitext(sys.argv[2])[0]}_1{os.path.splitext(sys.argv[2])[1]}", width, height, bpp)
IndexError: list index out of range
```

**Comment by raulmrio28-git** [comment]
Sorry for a very late reply, but to use this decoder you should type into the command prompt:
``paf_decoder.py (PAF file) (PAF file).png``
Currently, the rewritten version uses a GUI, making the preview of a PDK Animation easier
